import { ApiRequest, ApiResponse } from 'react-auto-crud';

import { Task } from '../../models/task';
import { ITaskDatasource } from '../datasources/task-datasource.interface';

/**
 * Task repository
 * Handles business logic and data transformation between datasource and UI
 */
export class TaskRepository {
    constructor(private datasource: ITaskDatasource) { }

    /**
     * Fetch tasks with server-side filtering, sorting, and pagination
     * Compatible with AutoTable component requirements
     */
    async fetchTasks(request: ApiRequest): Promise<ApiResponse<Task>> {
        return this.datasource.queryData(request);
    }

    /**
     * Create a new task
     */
    async createTask(data: Partial<Task>): Promise<Task> {
        // Ensure required fields are present
        if (!data.title) {
            throw new Error('Title is required');
        }

        // Remove id, createdAt, updatedAt if provided (they will be generated by datasource)
        return this.datasource.create({
            title: data.title,
            description: data.description,
            status: data.status || 'todo',
            priority: data.priority || 'medium',
            dueDate: data.dueDate,
        });
    }

    /**
     * Update an existing task
     */
    async updateTask(id: string | number, data: Partial<Task>): Promise<Task> {
        return this.datasource.update(String(id), data);
    }

    /**
     * Delete a task
     */
    async deleteTask(id: string | number): Promise<void> {
        return this.datasource.delete(String(id));
    }
}
